/*
Initially Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";
import { ACESFilmicToneMapping } from "three";
import { useThree } from "@react-three/fiber";
import japanModel from "../../model/japanStreet.gltf";

export default function Model({ onLightClick, lightStatus, ...props }) {
  const { nodes, materials } = useGLTF(japanModel);
  const light = useRef();

  const handleOnLightClick = (e) => {
    if (light.current) {
      onLightClick(!light.current.visible);
    }
    e.stopPropagation();
  };

  useThree((x) => {
    const { camera, gl: renderer } = x;

    renderer.toneMapping = Number(ACESFilmicToneMapping);
    renderer.toneMappingExposure = Math.pow(2, -3.33);
    renderer.physicallyCorrectLights = true;
    renderer.setClearColor(0xcccccc);

    camera.position.x = -2;
    camera.position.y = 2.795891180244544;
    camera.position.z = 4.054090974207679;
    camera.fov = 50;
  });

  return (
    <group {...props} dispose={null}>
      <group position={[5.78, 3.72, 0.9]} rotation={[1.89, 0.88, -2.05]}>
        <directionalLight
          decay={3}
          color="#7d87ff"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[0, 0, 0]}>
        <PerspectiveCamera makeDefault={false} far={100} near={0.1} />
      </group>
      <group position={[2.11, 3.48, -0.74]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff3100"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[2.99, 4.67, -0.34]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff8e35"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-1.44, 2.3, -0.82]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff3a09"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-0.92, 2.3, -0.82]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff3a09"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-0.83, 3.48, -0.68]}>
        <pointLight
          intensity={50}
          decay={2}
          color="#ff3a09"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-1.42, 3.48, -0.68]}>
        <pointLight
          intensity={50}
          decay={2}
          color="#ff3a09"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[0.84, 3.48, -0.68]}>
        <pointLight
          intensity={49.4}
          decay={2}
          color="#ff3a09"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-1.42, 2.17, 0.14]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff4b08"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-3.14, 2.3, -0.66]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff0300"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-2.93, 3.32, -0.66]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff5523"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-2.19, 3.32, -0.66]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff5523"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-4.35, 3.32, -0.66]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff5523"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-3.62, 3.32, -0.66]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff5523"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-5.72, 5.27, -0.55]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff843b"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-6.41, 5.27, -0.52]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff843b"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-7.25, 5.27, -0.49]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff843b"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-9.16, 5.27, -0.43]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff2214"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-9.85, 5.27, -0.43]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff0001"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-10.69, 5.27, -0.43]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff0002"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-8.94, 1.98, -0.55]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff3828"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-10.03, 1.98, -0.43]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff0907"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-11.07, 1.98, -0.43]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff0000"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[0.69, 3.66, -0.05]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff0400"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-0.3, 3.66, -0.05]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff0400"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-1.33, 3.66, -0.05]}>
        <pointLight
          ref={light}
          intensity={100}
          decay={2}
          color="#ff0400"
          rotation={[-Math.PI / 2, 0, 0]}
          visible={lightStatus}
        />
      </group>
      <group position={[-0.83, 4.21, -0.05]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff1204"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-2.68, 5.27, -0.14]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff0900"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-5.32, 1.62, -0.96]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ffc4a9"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-6.54, 1.62, -0.96]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ffc4a9"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[4.22, 1.62, -0.96]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ffc4a9"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[4.22, 3.05, -0.96]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ffc4a9"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[1.56, 3.48, -0.74]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff3100"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[3.2, 3.48, -0.74]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff3100"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[2.66, 3.48, -0.74]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff3100"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[2.33, 2.23, -0.74]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff3100"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[3.08, 2.23, -0.74]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff3100"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[1.59, 2.23, -0.74]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff3100"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[2.33, 1.18, -0.74]}>
        <pointLight
          intensity={100}
          decay={2}
          color="#ff3100"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[1.38, 1.07, -0.68]} scale={0.25}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001.geometry}
          material={materials["Plant Leaf"]}
          position={[0, -0.19, 0]}
          scale={2.67}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle002.geometry}
          material={materials["Plant Leaf"]}
          position={[0.89, -0.45, 0]}
          rotation={[0, -0.6, 0]}
          scale={2.33}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle003.geometry}
          material={materials["Plant Leaf"]}
          position={[1.9, -0.33, 0.18]}
          rotation={[-Math.PI, 0.72, -Math.PI]}
          scale={[2.48, 2.71, 2.48]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle004.geometry}
          material={materials["Plant Leaf"]}
          position={[-22.85, -0.17, 0.62]}
          rotation={[-Math.PI, 0.72, -Math.PI]}
          scale={[2.64, 2.88, 2.64]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle005.geometry}
          material={materials["Plant Leaf"]}
          position={[-13.4, -0.65, 0.56]}
          rotation={[-Math.PI, 0.72, -Math.PI]}
          scale={[1.94, 2.12, 1.94]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002.geometry}
          material={materials["Plant Stem"]}
          position={[0, -0.19, 0]}
          scale={2.67}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003.geometry}
          material={materials["Plant Stem"]}
          position={[0.89, -0.45, 0]}
          rotation={[0, -0.6, 0]}
          scale={2.33}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004.geometry}
          material={materials["Plant Stem"]}
          position={[1.85, -0.33, 0]}
          rotation={[-Math.PI, 0.72, -Math.PI]}
          scale={[2.48, 2.71, 2.48]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005.geometry}
          material={materials["Plant Stem"]}
          position={[-22.85, -0.17, 0]}
          rotation={[-Math.PI, 0.72, -Math.PI]}
          scale={[2.64, 2.88, 2.64]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006.geometry}
          material={materials["Plant Stem"]}
          position={[-13.4, -0.65, 0]}
          rotation={[-Math.PI, 0.72, -Math.PI]}
          scale={[1.94, 2.12, 1.94]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.Asphalt}
        position={[-4.65, 0.31, 1.6]}
        scale={[10.66, 0.26, 4.4]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials["Emerald Green Wall Paint"]}
        position={[5.34, 2.41, -1.44]}
        scale={[0.59, 1.67, 0.84]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials["Emerald Green Wall Paint"]}
        position={[4.66, 2.41, -1.44]}
        scale={[0.08, 1.67, 0.84]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials["Emerald Green Wall Paint"]}
        position={[3.51, 2.41, -1.44]}
        scale={[0.08, 1.67, 0.84]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials["Emerald Green Wall Paint"]}
        position={[2.91, 3.91, -1.44]}
        scale={[-1.66, -0.17, 0.84]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials["Emerald Green Wall Paint"]}
        position={[1.17, 2.41, -1.44]}
        scale={[0.08, 1.67, 0.84]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials["Concrete Wall Panels"]}
        position={[2.34, 3.06, -1.44]}
        scale={[-1.12, -0.06, 0.79]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials["Emerald Green Wall Paint"]}
        position={[2.34, 2.96, -1.44]}
        scale={[-1.12, -0.06, 0.73]}
      />
      <group
        position={[1.8, 3.42, -0.71]}
        rotation={[1.5, 0, 0]}
        scale={[-0.54, -0.03, 0.31]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_1.geometry}
          material={materials["Brushed Metal Radial polish"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_2.geometry}
          material={materials["Material.012"]}
        />
      </group>
      <group
        position={[2.88, 3.42, -0.71]}
        rotation={[1.53, 0, 0]}
        scale={[-0.54, -0.03, 0.31]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_1.geometry}
          material={materials["Brushed Metal Radial polish"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_2.geometry}
          material={materials["Material.012"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials["Brushed Metal Radial polish"]}
        position={[4.08, 3.67, -0.66]}
        rotation={[-0.12, 0, 0]}
        scale={[-0.5, -0.06, 0.01]}
      />
      <group
        position={[2.35, 1.81, -0.83]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[-1.07, -0.05, 1.08]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012_1.geometry}
          material={materials["Brushed Metal Radial polish"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012_2.geometry}
          material={materials["Material.012"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={materials["Material.004"]}
        position={[-0.37, 3.91, -1.44]}
        scale={[-1.46, -0.17, 0.84]}
      />
      <group position={[-0.37, 3.48, -0.71]} scale={[-1.46, -0.26, -0.06]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_1.geometry}
          material={materials["wood decoration wall"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_2.geometry}
          material={materials["Material.012"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={materials["wood decoration wall"]}
        position={[-0.37, 3.16, -1.44]}
        scale={[-1.46, -0.06, 0.81]}
      />
      <group
        position={[0.67, 2.24, -0.75]}
        rotation={[Math.PI / 2, 0, 0.19]}
        scale={[-0.42, -0.04, 0.68]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_1.geometry}
          material={materials["wood decoration wall"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_2.geometry}
          material={materials["Material.014"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        material={materials["Concrete Wall Panels"]}
        position={[-0.37, 3.02, -1.44]}
        scale={[-1.46, -0.09, 0.84]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={materials["Metal Roof 02"]}
        position={[-0.37, 3.84, -0.19]}
        scale={[-1.46, -0.02, 0.41]}
      />
      <group
        position={[-1.23, 2.33, -0.81]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[-0.59, -0.06, 0.61]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_1.geometry}
          material={materials["wood decoration wall"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_2.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_3.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={materials["wood decoration wall"]}
        position={[-1.18, 2.87, -0.97]}
        scale={[-0.65, -0.09, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020.geometry}
        material={materials.Material}
        position={[-1.16, 0.86, -0.67]}
        rotation={[-Math.PI, 1.36, -Math.PI]}
        scale={[0.15, 0.12, 0.15]}
      />
      <group position={[-4.51, 0.64, -1.28]} scale={[-10.51, -0.09, 0.88]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube023_1.geometry}
          material={materials["Concrete Wall Panels"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube023_2.geometry}
          material={materials["Clay Orange"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022.geometry}
        material={materials["Material.001"]}
        position={[-1.59, 0.92, -0.6]}
        scale={0.18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube023.geometry}
        material={materials["Clay Orange"]}
        position={[-3.29, 3.91, -1.44]}
        scale={[-1.46, -0.17, 0.84]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube024.geometry}
        material={materials["Metal Roof 02"]}
        position={[-3.29, 3.69, -1.44]}
        scale={[-1.46, 0.04, 1.17]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube025.geometry}
        material={materials["Clay Orange"]}
        position={[-3.29, 3.59, -1.44]}
        scale={[-1.46, 0.04, 1.09]}
      />
      <group position={[-3.29, 3.32, -1.44]} scale={[-1.46, -0.24, 0.84]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028_1.geometry}
          material={materials["Clay Orange"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028_2.geometry}
          material={materials["Material.011"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube027.geometry}
        material={materials["Clay Orange"]}
        position={[-3.29, 2.98, -1.44]}
        scale={[-1.46, -0.11, 0.84]}
      />
      <group position={[-3.29, 1.8, -1.44]} scale={[-1.46, -1.05, 0.84]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube031_1.geometry}
          material={materials["Brushed Metal Radial polish"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube031_2.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube031_3.geometry}
          material={materials["Clay Orange"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube029.geometry}
        material={materials["White Bricks"]}
        position={[-6.38, 3.62, -1.36]}
        scale={[-1.63, -0.46, 0.93]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube030.geometry}
        material={nodes.Cube030.material}
        position={[-6.38, 2.99, -1.36]}
        scale={[-1.63, -0.19, 0.7]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube031.geometry}
        material={materials["Concrete Wall Panels"]}
        position={[-7.3, 1.7, -1.36]}
        scale={[-0.09, -1.11, 0.84]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube032.geometry}
        material={materials["Brushed Metal Radial polish"]}
        position={[-6.58, 2.78, -0.66]}
        rotation={[-0.12, 0, 0]}
        scale={[-0.62, -0.06, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube033.geometry}
        material={materials["Brushed Metal Radial polish"]}
        position={[-5.31, 2.78, -0.66]}
        rotation={[-0.12, 0, 0]}
        scale={[-0.62, -0.06, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube034.geometry}
        material={materials["Wood Painted White"]}
        position={[-5.94, 1.73, -1.36]}
        scale={[-0.04, -1.11, 0.84]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube035.geometry}
        material={materials["Concrete Wall Panels"]}
        position={[-8.41, 1.7, -1.36]}
        scale={[-0.09, -1.11, 0.84]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube036.geometry}
        material={materials["Wood Painted White"]}
        position={[-6.38, 2.86, -1.36]}
        scale={[-1.63, 0.05, 0.84]}
      />
      <group position={[-9.84, 2.4, -1.36]} scale={[-1.35, -1.66, 0.84]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube043_1.geometry}
          material={materials["Red Fur"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube043_2.geometry}
          material={materials["Material.011"]}
        />
      </group>
      <group position={[1.85, 0.89, -0.62]} scale={[0.13, 0.17, 0.14]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_2.geometry}
          material={materials["Clay Orange"]}
        />
      </group>
      <group position={[1.6, 0.88, -0.68]} scale={[0.1, 0.15, 0.14]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_2.geometry}
          material={materials["Clay Orange"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials["Material.006"]}
        position={[2.02, 0.78, -0.66]}
        scale={[0.09, 0.06, 0.11]}
      />
      <group position={[1.39, 0.91, -0.64]} scale={[0.12, 0.18, 0.15]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_2.geometry}
          material={materials["Clay Orange"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials["Material.006"]}
        position={[-2.03, 0.85, -0.51]}
        scale={[0.15, 0.11, 0.15]}
      />
      <group
        position={[0.7, 3.81, -0.22]}
        rotation={[-0.38, 0, 0]}
        scale={[0.1, 0.14, 0.1]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_1.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_2.geometry}
          material={materials["Material.011"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube039.geometry}
        material={materials["Steel lattice"]}
        position={[-0.86, 3.84, -0.19]}
        scale={[-0.03, -0.03, 0.43]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube040.geometry}
        material={materials["Steel lattice"]}
        position={[0.2, 3.84, -0.19]}
        scale={[-0.03, -0.03, 0.43]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube041.geometry}
        material={materials["Iron Touched"]}
        position={[0.69, 3.81, -0.39]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.04, -0.01, 0.21]}
      />
      <group
        position={[-0.3, 3.81, -0.22]}
        rotation={[-0.57, 0, 0]}
        scale={[0.1, 0.14, 0.1]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube036_1.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube036_2.geometry}
          material={materials["Material.011"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube043.geometry}
        material={materials["Iron Touched"]}
        position={[-0.3, 3.81, -0.39]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.04, -0.01, 0.21]}
      />
      <group
        position={[-1.35, 3.81, -0.22]}
        rotation={[-0.38, 0, 0]}
        scale={[0.1, 0.14, 0.1]}
        onClick={handleOnLightClick}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube044_1.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube044_2.geometry}
          material={materials["Material.011"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube045.geometry}
        material={materials["Iron Touched"]}
        position={[-1.35, 3.81, -0.39]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.04, -0.01, 0.21]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube046.geometry}
        material={materials["wood decoration wall"]}
        position={[-0.33, 5.46, -1.48]}
        scale={[-1.58, -1.46, 0.74]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube047.geometry}
        material={materials["Concrete Wall Panels"]}
        position={[3.58, 5.47, -1.47]}
        scale={[-2.34, -1.45, 0.8]}
      />
      <group position={[2.99, 4.7, -0.64]} scale={[0.65, 0.49, 0.07]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_1.geometry}
          material={materials["Plant Stem"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_2.geometry}
          material={materials["Material.012"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube049.geometry}
        material={materials["Brushed Metal Radial polish"]}
        position={[0.69, 4.55, -0.49]}
        scale={[0.39, 0.3, 0.21]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube050.geometry}
        material={nodes.Cube050.material}
        position={[1, 4.23, -0.5]}
        scale={[0.05, 0.03, 0.21]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube051.geometry}
        material={nodes.Cube051.material}
        position={[0.43, 4.23, -0.5]}
        scale={[0.05, 0.03, 0.21]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube052.geometry}
        material={materials["Brushed Metal Radial polish"]}
        position={[-0.33, 4.55, -0.49]}
        scale={[0.39, 0.3, 0.21]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube053.geometry}
        material={nodes.Cube053.material}
        position={[-0.02, 4.23, -0.5]}
        scale={[0.05, 0.03, 0.21]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube054.geometry}
        material={nodes.Cube054.material}
        position={[-0.59, 4.23, -0.5]}
        scale={[0.05, 0.03, 0.21]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube055.geometry}
        material={materials["Brushed Metal Radial polish"]}
        position={[-1.36, 4.55, -0.49]}
        scale={[0.39, 0.3, 0.21]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube056.geometry}
        material={nodes.Cube056.material}
        position={[-1.04, 4.23, -0.5]}
        scale={[0.05, 0.03, 0.21]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube057.geometry}
        material={nodes.Cube057.material}
        position={[-1.61, 4.23, -0.5]}
        scale={[0.05, 0.03, 0.21]}
      />
      <group
        position={[-0.83, 4.38, -0.18]}
        rotation={[-0.57, 0, 0]}
        scale={[0.13, 0.17, 0.13]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_2.geometry}
          material={materials["Material.011"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube059.geometry}
        material={materials["Iron Touched"]}
        position={[-0.83, 4.38, -0.43]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.06, -0.01, 0.32]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube060.geometry}
        material={nodes.Cube060.material}
        position={[-0.83, 4.21, -0.46]}
        rotation={[-0.61, 0, 0]}
        scale={[-0.06, -0.01, 0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube061.geometry}
        material={materials["Clay Orange"]}
        position={[-3.32, 5.46, -1.48]}
        scale={[-1.42, -1.46, 0.74]}
      />
      <group
        position={[-2.84, 5.46, -0.3]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[-0.37, -0.92, 0.11]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube050_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube050_2.geometry}
          material={materials["Material.012"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube063.geometry}
        material={materials["Iron Touched"]}
        position={[-2.84, 6.18, -0.7]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[-0.03, -0.03, 0.11]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube064.geometry}
        material={materials["Concrete Wall Panels"]}
        position={[-3.29, 4.26, -1.44]}
        scale={[-1.46, -0.07, 0.84]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube065.geometry}
        material={materials["White Bricks"]}
        position={[-6.38, 5.49, -1.36]}
        scale={[-1.63, -1.43, 0.84]}
      />
      <group position={[-6.59, 5.34, -0.47]} scale={[1.19, 0.9, 0.06]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube066_1.geometry}
          material={materials["Brushed Metal Radial polish"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube066_2.geometry}
          material={materials["Material.012"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube067.geometry}
        material={materials["iron brushed"]}
        position={[-9.84, 3.47, -0.46]}
        scale={[-1.21, -0.3, 0.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube068.geometry}
        material={materials["Red Fur"]}
        position={[-9.84, 5.5, -1.36]}
        scale={[-1.35, -1.43, 0.84]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube069.geometry}
        material={materials["iron brushed"]}
        position={[-9.84, 3.91, -0.46]}
        scale={[-1.21, -0.05, 0.08]}
      />
      <group position={[-10.05, 5.34, -0.47]} scale={[1.19, 0.9, 0.06]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube070_1.geometry}
          material={materials["Clay Orange"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube070_2.geometry}
          material={materials["Material.011"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube071.geometry}
        material={materials["Material.007"]}
        position={[3.52, 1.87, -0.55]}
        scale={[0.06, 0.17, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube072.geometry}
        material={materials["Asphalt rough"]}
        position={[-4.51, 0.53, -0.25]}
        scale={[-10.52, -0.09, 0.29]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={materials["iron brushed"]}
        position={[0.8, 4.55, -0.26]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.2, 0.04, 0.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube073.geometry}
        material={nodes.Cube073.material}
        position={[0.8, 4.56, -0.29]}
        rotation={[0, 0, 0.77]}
        scale={[0.07, 0.04, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={nodes.Cylinder006.material}
        position={[0.8, 4.56, -0.28]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.05}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube074.geometry}
        material={nodes.Cube074.material}
        position={[0.8, 4.56, -0.29]}
        rotation={[0, 0, 2.34]}
        scale={[0.07, 0.04, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube075.geometry}
        material={nodes.Cube075.material}
        position={[0.8, 4.56, -0.29]}
        rotation={[0, 0, -2.38]}
        scale={[0.07, 0.04, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube076.geometry}
        material={nodes.Cube076.material}
        position={[0.8, 4.56, -0.29]}
        rotation={[0, 0, -0.81]}
        scale={[0.07, 0.04, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube077.geometry}
        material={materials["Iron Touched"]}
        position={[0.68, 4.56, -0.23]}
        scale={[0.01, 0.13, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube078.geometry}
        material={materials["Iron Touched"]}
        position={[0.7, 4.56, -0.23]}
        scale={[0.01, 0.15, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube079.geometry}
        material={materials["Iron Touched"]}
        position={[0.73, 4.56, -0.23]}
        scale={[0.01, 0.16, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube080.geometry}
        material={materials["Iron Touched"]}
        position={[0.75, 4.56, -0.23]}
        scale={[0.01, 0.17, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube081.geometry}
        material={materials["Iron Touched"]}
        position={[0.78, 4.56, -0.23]}
        scale={[0.01, 0.18, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube082.geometry}
        material={materials["Iron Touched"]}
        position={[0.8, 4.56, -0.23]}
        scale={[0.01, 0.18, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube083.geometry}
        material={materials["Iron Touched"]}
        position={[0.92, 4.56, -0.23]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.01, 0.13, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube084.geometry}
        material={materials["Iron Touched"]}
        position={[0.9, 4.56, -0.23]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.01, 0.15, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube085.geometry}
        material={materials["Iron Touched"]}
        position={[0.87, 4.56, -0.23]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.01, 0.16, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube086.geometry}
        material={materials["Iron Touched"]}
        position={[0.85, 4.56, -0.23]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.01, 0.17, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube087.geometry}
        material={materials["Iron Touched"]}
        position={[0.83, 4.56, -0.23]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.01, 0.18, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube088.geometry}
        material={materials["Iron Touched"]}
        position={[0.66, 4.56, -0.23]}
        scale={[0.01, 0.11, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube089.geometry}
        material={materials["Iron Touched"]}
        position={[0.94, 4.56, -0.23]}
        scale={[0.01, 0.11, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder007.geometry}
        material={materials["iron brushed"]}
        position={[-0.2, 4.55, -0.26]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.2, 0.04, 0.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube090.geometry}
        material={nodes.Cube090.material}
        position={[-0.2, 4.56, -0.29]}
        rotation={[0, 0, 0.77]}
        scale={[0.07, 0.04, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder008.geometry}
        material={nodes.Cylinder008.material}
        position={[-0.2, 4.56, -0.28]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.05}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube091.geometry}
        material={nodes.Cube091.material}
        position={[-0.2, 4.56, -0.29]}
        rotation={[0, 0, 2.34]}
        scale={[0.07, 0.04, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube092.geometry}
        material={nodes.Cube092.material}
        position={[-0.2, 4.56, -0.29]}
        rotation={[0, 0, -2.38]}
        scale={[0.07, 0.04, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube093.geometry}
        material={nodes.Cube093.material}
        position={[-0.2, 4.56, -0.29]}
        rotation={[0, 0, -0.81]}
        scale={[0.07, 0.04, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube094.geometry}
        material={materials["Iron Touched"]}
        position={[-0.32, 4.56, -0.23]}
        scale={[0.01, 0.13, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube095.geometry}
        material={materials["Iron Touched"]}
        position={[-0.3, 4.56, -0.23]}
        scale={[0.01, 0.15, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube096.geometry}
        material={materials["Iron Touched"]}
        position={[-0.27, 4.56, -0.23]}
        scale={[0.01, 0.16, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube097.geometry}
        material={materials["Iron Touched"]}
        position={[-0.25, 4.56, -0.23]}
        scale={[0.01, 0.17, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube098.geometry}
        material={materials["Iron Touched"]}
        position={[-0.22, 4.56, -0.23]}
        scale={[0.01, 0.18, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube099.geometry}
        material={materials["Iron Touched"]}
        position={[-0.2, 4.56, -0.23]}
        scale={[0.01, 0.18, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube100.geometry}
        material={materials["Iron Touched"]}
        position={[-0.08, 4.56, -0.23]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.01, 0.13, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube101.geometry}
        material={materials["Iron Touched"]}
        position={[-0.1, 4.56, -0.23]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.01, 0.15, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube102.geometry}
        material={materials["Iron Touched"]}
        position={[-0.13, 4.56, -0.23]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.01, 0.16, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube103.geometry}
        material={materials["Iron Touched"]}
        position={[-0.15, 4.56, -0.23]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.01, 0.17, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube104.geometry}
        material={materials["Iron Touched"]}
        position={[-0.18, 4.56, -0.23]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.01, 0.18, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube105.geometry}
        material={materials["Iron Touched"]}
        position={[-0.35, 4.56, -0.23]}
        scale={[0.01, 0.11, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube106.geometry}
        material={materials["Iron Touched"]}
        position={[-0.06, 4.56, -0.23]}
        scale={[0.01, 0.11, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder009.geometry}
        material={materials["iron brushed"]}
        position={[-1.22, 4.55, -0.26]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.2, 0.04, 0.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube107.geometry}
        material={nodes.Cube107.material}
        position={[-1.22, 4.56, -0.29]}
        rotation={[0, 0, 0.77]}
        scale={[0.07, 0.04, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010.geometry}
        material={nodes.Cylinder010.material}
        position={[-1.22, 4.56, -0.28]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.05}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube108.geometry}
        material={nodes.Cube108.material}
        position={[-1.22, 4.56, -0.29]}
        rotation={[0, 0, 2.34]}
        scale={[0.07, 0.04, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube109.geometry}
        material={nodes.Cube109.material}
        position={[-1.22, 4.56, -0.29]}
        rotation={[0, 0, -2.38]}
        scale={[0.07, 0.04, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube110.geometry}
        material={nodes.Cube110.material}
        position={[-1.22, 4.56, -0.29]}
        rotation={[0, 0, -0.81]}
        scale={[0.07, 0.04, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube111.geometry}
        material={materials["Iron Touched"]}
        position={[-1.34, 4.56, -0.23]}
        scale={[0.01, 0.13, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube112.geometry}
        material={materials["Iron Touched"]}
        position={[-1.32, 4.56, -0.23]}
        scale={[0.01, 0.15, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube113.geometry}
        material={materials["Iron Touched"]}
        position={[-1.29, 4.56, -0.23]}
        scale={[0.01, 0.16, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube114.geometry}
        material={materials["Iron Touched"]}
        position={[-1.27, 4.56, -0.23]}
        scale={[0.01, 0.17, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube115.geometry}
        material={materials["Iron Touched"]}
        position={[-1.24, 4.56, -0.23]}
        scale={[0.01, 0.18, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube116.geometry}
        material={materials["Iron Touched"]}
        position={[-1.22, 4.56, -0.23]}
        scale={[0.01, 0.18, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube117.geometry}
        material={materials["Iron Touched"]}
        position={[-1.1, 4.56, -0.23]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.01, 0.13, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube118.geometry}
        material={materials["Iron Touched"]}
        position={[-1.12, 4.56, -0.23]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.01, 0.15, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube119.geometry}
        material={materials["Iron Touched"]}
        position={[-1.15, 4.56, -0.23]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.01, 0.16, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube120.geometry}
        material={materials["Iron Touched"]}
        position={[-1.17, 4.56, -0.23]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.01, 0.17, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube121.geometry}
        material={materials["Iron Touched"]}
        position={[-1.19, 4.56, -0.23]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.01, 0.18, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube122.geometry}
        material={materials["Iron Touched"]}
        position={[-1.36, 4.56, -0.23]}
        scale={[0.01, 0.11, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube123.geometry}
        material={materials["Iron Touched"]}
        position={[-1.08, 4.56, -0.23]}
        scale={[0.01, 0.11, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube124.geometry}
        material={materials["Material.008"]}
        position={[-3.53, 3.62, -2.38]}
        scale={[8.37, 3.03, 0.38]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube125.geometry}
        material={materials["Clay Orange"]}
        position={[3.2, 0.86, -0.64]}
        rotation={[0, 0.19, 0]}
        scale={0.13}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube126.geometry}
        material={materials["Iron Touched"]}
        position={[3.22, 0.89, -0.5]}
        rotation={[0, 0.19, 0]}
        scale={[0.07, 0.04, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder011.geometry}
        material={materials["Material.010"]}
        position={[3.86, 0.8, 0.39]}
        rotation={[0, 0.37, 0]}
        scale={0.16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder012.geometry}
        material={materials["Material.010"]}
        position={[3.86, 0.84, 0.39]}
        rotation={[0, 0.37, 0]}
        scale={0.16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder013.geometry}
        material={materials["Material.010"]}
        position={[3.86, 0.88, 0.39]}
        rotation={[0, 0.29, 0]}
        scale={0.16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder014.geometry}
        material={materials["Material.010"]}
        position={[5.15, 0.83, -0.13]}
        rotation={[0, 0.21, 0]}
        scale={0.16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder015.geometry}
        material={materials["iron brushed"]}
        position={[4.5, 1.17, 0.13]}
        rotation={[0.19, 0.37, -1.7]}
        scale={[0.02, 0.72, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube127.geometry}
        material={materials["Concrete Wall Panels"]}
        position={[2.4, 0.67, -0.23]}
        scale={[0.21, 0.05, 0.17]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder016.geometry}
        material={materials["Material.002"]}
        position={[-0.68, 0.99, -0.56]}
        rotation={[-Math.PI, 1.41, -Math.PI]}
        scale={[0.13, 0.21, 0.13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube128.geometry}
        material={materials["Emerald Green Wall Paint"]}
        position={[-1.14, 0.78, 0.32]}
        rotation={[0, -0.14, 0]}
        scale={[0.18, 0.21, 0.23]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube129.geometry}
        material={materials.Material}
        position={[-1.16, 0.73, -0.17]}
        rotation={[-Math.PI, 0.36, -Math.PI]}
        scale={[0.15, 0.12, 0.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder017.geometry}
        material={materials["Material.006"]}
        position={[-0.91, 0.71, 0]}
        rotation={[-3.05, 0, 0]}
        scale={[0.12, 0.09, 0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder018.geometry}
        material={materials["iron brushed"]}
        position={[-1.41, 1.63, -0.34]}
        scale={[0.02, -1.06, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube130.geometry}
        material={materials["Material.005"]}
        position={[-2.49, 1.01, 0.5]}
        rotation={[0, -1.49, 0.44]}
        scale={[0.03, 0.53, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube134.geometry}
        material={materials["Material.005"]}
        position={[-2.08, 1.57, 0.23]}
        rotation={[0, -1.49, 0]}
        scale={[0.05, 0.06, 0.53]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube131.geometry}
        material={materials["wood decoration wall"]}
        position={[-1.14, 2.68, 0.16]}
        rotation={[0, 0, Math.PI / 4]}
        scale={[0.01, 0.07, 0.19]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube132.geometry}
        material={materials["wood decoration wall"]}
        position={[-1.68, 2.68, 0.16]}
        rotation={[0, 0, -Math.PI / 4]}
        scale={[0.01, 0.07, 0.19]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube133.geometry}
        material={materials["wood decoration wall"]}
        position={[-1.42, 2.97, 0.16]}
        scale={[0.03, 0.03, 0.21]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["Material.008"]}
        position={[-1.59, 2.81, 0.16]}
        rotation={[0, 0, Math.PI / 4]}
        scale={[0.24, 0.24, 0.22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials["Material.008"]}
        position={[-1.24, 2.81, 0.16]}
        rotation={[0, 0, -Math.PI / 4]}
        scale={[0.24, 0.24, 0.22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube135.geometry}
        material={materials["Material.003"]}
        position={[-1.41, 2.15, 0.13]}
        scale={[0.22, 0.4, 0.22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder019.geometry}
        material={materials["iron brushed"]}
        position={[-1.41, 2.66, -0.09]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.02, -0.26, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube136.geometry}
        material={materials["Concrete Wall Panels"]}
        position={[-3.17, 0.67, -0.23]}
        scale={[0.21, 0.05, 0.17]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder020.geometry}
        material={materials["Material.006"]}
        position={[-4.41, 0.9, -0.51]}
        scale={[0.15, 0.18, 0.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube137.geometry}
        material={materials["Concrete Wall Panels"]}
        position={[-5.98, 0.67, -0.23]}
        scale={[1.18, 0.05, 0.17]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube138.geometry}
        material={materials["iron brushed"]}
        position={[-7.31, 1.84, -0.4]}
        scale={[0.12, 0.08, 0.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube139.geometry}
        material={nodes.Cube139.material}
        position={[-7.29, 1.84, -0.51]}
        scale={-0.03}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube140.geometry}
        material={materials["Material.008"]}
        position={[-14.44, 3.62, -1.72]}
        scale={[-0.42, 3.03, 1.59]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube141.geometry}
        material={nodes.Cube141.material}
        position={[-4.51, 0.48, 0.75]}
        scale={[-10.52, -0.09, 0.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials["iron brushed"]}
        position={[-4.33, 2.02, -0.66]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text001.geometry}
        material={materials["Iron Touched"]}
        position={[-1.18, 2.33, 0.14]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text002.geometry}
        material={nodes.Text002.material}
        position={[-1.41, 2.33, 0.36]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube142.geometry}
        material={nodes.Cube142.material}
        position={[-4.51, 0.48, 5.44]}
        scale={[-10.52, -0.09, 0.08]}
      />
    </group>
  );
}

useGLTF.preload(japanModel);
